deploy:
  stage: build
  script:
    - npm run deploy

before_script:
  - sudo apt-get install -y build-essential
  - sudo apt-get install ruby
  - sudo gem install sass
  - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g npm@3.7.3
